### ISSUE TITLE
Aether does not load in Ardour 6.6

### ISSUE THREAD

**Issue by unfa** [Dougal-s/Aether#1]
I have this error in Ardour's log window:

`2021-04-16T23:57:00 [WARNING]: Unsupported required LV2 feature: 'http://lv2plug.in/ns/ext/port-props#supportsStrictBounds' in 'Aether'.`

**Comment by Dougal-s** [comment]
Thanks for the error!
Hopefully it should be fixed in the ttl file in the master branch. Just replace the old `aether.ttl` in the lv2 directory with the one in the master branch [here](https://github.com/Dougal-s/Aether/blob/master/aether.lv2/aether.ttl).
