### ISSUE TITLE
No GUI in Carla

### ISSUE THREAD

**Issue by unfa** [Dougal-s/Aether#2]
I've tried loading Aether in Carla (2.3.0-alpha2), and it loaded fine, though I was only able to use the generic UI.

The custom UI does not show up.

I'm running Manjaro Linux with KDE.

**Comment by sjaehn** [comment]
Hmmm, I successfully used Aether in Carla 2.3.0-RC2 (ubuntu/focal). It works fine. Also the custom UI. But I used the 17 days old build, not the current master.

**Comment by Dougal-s** [comment]
Interesting. If there isn't anything in the log tab in carla, the only thing I can think of is that maybe it was trying to dynamically link to a library that doesn't exist? I'll try setting up a Manjaro VM today and hopefully figure out whats going wrong!

**Comment by unfa** [comment]
I checked but there was zero console output when I loaded and attempted to
open Aether's UI in Carla.

**Comment by SpotlightKid** [comment]
Here on Manjaro Aether builds and `make test` shows no failing tests, but the plugin crashes with a segfault on loading in Carla and jalv.

**Comment by MyLoFy** [comment]
On archlinux it doesn't crash zrythm 1.0.0-alpha.15.0.1-8-g62aa25490 only if fully bridged. However, GUI won't open:

```
Trying to get window...
Carla assertion failure: "fProcess != nullptr" in file CarlaPluginBridge.cpp, line 131
```

Aether also segfaults MusE 4pre3 and Qtractor.

**Comment by jpcima** [comment]
I've traced the GUI issue here to this GL hint.
`		setHint(pugl::ViewHint::samples, 16);`

It's too much for my graphics setup, but a lower value like 2 is working.
It fails with `PUGL_CREATE_CONTEXT_FAILED`, so it'd be nice to try downgrading the context if this case happens.

**Comment by Dougal-s** [comment]
Thanks for the help! I've lowered the samples to 2 and lowered the OpenGL context to version 3.3. A compiled plugin should be available as an artifact under the last run in the actions tab [here](https://github.com/Dougal-s/Aether/actions/runs/759259104).

**Comment by MyLoFy** [comment]
cool, thanks! GUI opens now on arch in carla, ardour, zrythm and qtractor.

**Comment by SpotlightKid** [comment]
Still no luck here. Apparently my laptop does not support GLSL 1.50

Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, and 3.00 ES

**Comment by Dougal-s** [comment]
My bad, I believe the problem was that I forgot to set `setHint(pugl::ViewHint::useCompatProfile, false)`. It seems that Mesa drivers do not support GLSL 1.50 when using OpenGL with a compatibility profile. It should now be fixed in the master branch.

**Comment by almet** [comment]
Hey, it seem to work properly with the latest master for me.

**Comment by unfa** [comment]
Yup, this seems to have been fixed. Thank you!
I intend to make a video about this plug-in in the near future.
