### ISSUE TITLE
Release with bundled sources

### ISSUE THREAD

**Issue by cbix** [Dougal-s/Aether#23]
To make packaging this easier for linux distributions, it would be great to have a tarball including all sources + submodules as a release asset. That way packagers don't have to rely on git and have a verifiable source file that is probably also a bit faster to fetch.

What many projects with lots of submodules do is have some CI workflow that runs on each tag and automatically creates binary + bundles and adds them to a release on GitHub, but I believe you'll find a way that suits you best :)

Anyway thanks for this project!!

**Comment by Dougal-s** [comment]
Thanks for the suggestion, I wasn't previously aware of that! I've created a CI workflow that automatically attaches binaries and a bundle to every release from now on.
