### ISSUE TITLE
What is the license of this project?

### ISSUE THREAD

**Issue by unfa** [Dougal-s/Aether#3]
The Cloudseed plug-in  is licensed under MIT, but I couldn't find any explicit information about Aether.

It is also MIT?

**Comment by Dougal-s** [comment]
Thats a good point. I haven't thought about that yet but I suppose I would be inclined to use the same MIT license. I would love to hear if anyone has some thoughts on the matter.

**Comment by Dougal-s** [comment]
I chose to go with the MIT license for this project.
