### ISSUE TITLE
Exception "unrecognized units used!" with LC_NUMERIC using comma separator

### ISSUE THREAD

**Issue by jpcima** [Dougal-s/Aether#4]
When using the locale `fr_FR@UTF-8`, `strtof` does not read the string past the `.` character.
So it gets a truncated value, a bad end pointer, and an exception thrown as it expects to see the unit.

**Comment by Dougal-s** [comment]
Huh I wasn't aware of that! I'm not familiar with locales so I don't know how to fix this or how to recreate this exception. Could you share which plugin host you used? I've tried running Carla, Jalv and Reaper with the french locale installed and the environment variable `LC_NUMERIC` set to `fr_FR.UTF8`, but they all seem to ignore the current locale.

**Comment by jpcima** [comment]
It's jalv, and setting `LC_NUMERIC=fr_FR.UTF-8`, while the global locale is `C`, definitely does it.
It would need to generate this locale in glibc beforehand (by locale-gen stuff).

for some potential solutions
- surround with uselocale/newlocale/freelocale API calls, which change locale of the running thread
  (not portable to Windows, which alternatively provides _sscanf_l)
- std::istringstream with `imbue(std::locale::classic())`

**Comment by Dougal-s** [comment]
Thanks for the help! The latest commit should have fixed the issue and you can find compiled binaries as artifacts under the last run in the actions tab [here](https://github.com/Dougal-s/Aether/actions/runs/759660986).
