### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by almet** [Dougal-s/Aether#8]
So, I've been able to compile and I've got the resulting .so files, but I'm not sure what I should do with them.

I've tried adding the build path to carla, but it doesn't seem to show. Any idea?

**Comment by Dougal-s** [comment]
Aether is an lv2 plugin, which uses .lv2 directories instead of .so files. So, you'll have to add the the directory containing `aether.lv2` to the search path, or put `aether.lv2` in `~/.lv2`.

**Comment by almet** [comment]
Fixed in https://github.com/Dougal-s/Aether/commit/794a751a3ad2404cb5e3c89c0d26dd2d68a07811.
It worked for me.
